### ISSUE TITLE
TRPC-like adapter for express

### ISSUE THREAD

**Issue by aaronvg** [fern-api/fern-typescript#402]
Just a suggestion -- TRPC (https://trpc.io/) is extremely popular these days for generating type-safe serverside express code. Would love Fern to either
1. Publish only typescript or preferrably Zod schema objects that I can use to build my own trpc express server
2. Publish an express server that uses trpc-like idioms, like being able to write my own type-safe middlewares and use the context in each API. E.g. query({ input, ctx }) => { ... }

**Comment by dannysheridan** [comment]
Would love to do this down the line, but not in the near-term roadmap (next quarters) so closing for now
