### ISSUE TITLE
Cannot see full fern type hint in VSCode after generating typescript types

### ISSUE THREAD

**Issue by aaronvg** [fern-api/fern-typescript#403]
I'm having issues with VSCode not showing me all the properties of a fern-generated type when hovering over it:

e.g. I see
```
(alias) interface SearchResult
import SearchResult
```

Instead of the actual full type:

```
(alias) type ISearchResponse = {
        content: string;
        score: number;
        metadata: {
            documentId: string;
            title: string;
            source: string;
            tags: string[];
            annotations: string[];
    }
   ```
   
   tsConfig:
   ```
 {
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES6",
    "allowJs": true,
    // "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "resolveJsonModule": true,
  },
  "include": ["src/**/*", "src/**/*.json"],
}
```

fern generator version 0.5.2

LMK if y'all have any ideas :)

**Comment by zachkirsch** [comment]
Sweet!

Seems that if we do `export type = ...` rather than `export interface`, the hover is better when hovering over the type. Not that this doesn't help when hovering over properties/variables.

Thanks for the tip in discord :)

**Comment by dsinghvi** [comment]
Reopening so that we `export type` as well

**Comment by dannysheridan** [comment]
closing as we haven't hear about this as an issue in 10 months
