### ISSUE TITLE
"socket hang up" error on subsequent request after Express server errors out once

### ISSUE THREAD

**Issue by aaronvg** [fern-api/fern-typescript#404]
Behavior:
1. Call an API expecting an error to be thrown (in our case, a GlooApiError).
2. Server returns the error -- all good so far.
3. Call another API on the server that should NOT error out
4. Call always fails with `GlooApiError: socket hang up`

My guess is it's the http client on the client-side not closing the connection when an error occurs. I'll try to verify by using a custom fetcher at some point. I tried commenting out the `next(error)` and the subsequent requests succeeded (and only after all requests went thru did the socket error get thrown), but that doesn't look like a fix.

Also another side-note -- noticed our "DocumentService.js" file (and other service files) has some `await error.send(res)`. Should it be res.send(error)? Probably not an issue but just looked off.

**Comment by aaronvg** [comment]
in our case the subsequent call succeeds if we wait like 1-2 secs.

**Comment by zachkirsch** [comment]
Hmmm very weird, surprised it hasn't come up before.

  - What versions of TS + express generators are you on?
  - Is the stacktrace from the `socket hang up` pointing to the first call or the second call?

`socket hang up` makes me think that the server is not receiving the request correctly. Are you able to check this with server logs? Is there possibly something with your deployment that could be causing this?

> Also another side-note -- noticed our "DocumentService.js" file (and other service files) has some `await error.send(res)`. Should it be res.send(error)? Probably not an issue but just looked off.

No, that's correct. The errors we generate for Fern have a `send` method that knows how to serialize itself and set the status code. `res.send(error)` wouldn't set the status code appropriately or serialize the response body.

```ts
export class SomeError extends errors.GlooApiError {
    constructor();
    send(res: express.Response): Promise<void>;
}
```

**Comment by zachkirsch** [comment]
_From DM_

- Only happens on localhost, not on prod 🤔 
- Adding sleep when running locally

Maybe the natural delay in prod of the network requests is equivalent to the `sleep()`?

No action needed rn

**Comment by dannysheridan** [comment]
closing as no action needed
