### ISSUE TITLE
Parse and validate number/integer query parameters

### ISSUE THREAD

**Issue by kafkas** [fern-api/fern-typescript#418]
Would be useful if the Express wrapper parsed and validated query params like `limit` that are defined as integers in the Fern definition. Fern does seem to allow integer query params but they are not validated in the generated code (as of 0.5.9) and are incorrectly typed as `number | null | undefined`. Also, they are not camelcased.

**Comment by dannysheridan** [comment]
closing as we're not focusing on server boilerplate codegen right now
