### ISSUE TITLE
Enum-keyed Records should be generated as Partials

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern-typescript#467]
Right now we generated Enum-keyed maps (`map<MyEnum, string>`) as `Record<MyEnum, string | undefined>`.

This is because in typescript if you do `Record<Enum, Value>` then typescript doesn't let you make an object that's missing any of the enum values. this makes backcompat really hard and also a lot of the time people don't want to include every enum in the keys.

However, in our implementation all the keys are required.

We should instead generated `Partial<Record<MyEnum, string>>`

**Comment by dannysheridan** [comment]
closing as we haven't gotten a customer request for this
