### ISSUE TITLE
Simplify default behavior and custom configuration

### ISSUE THREAD

**Issue by amckinney** [fern-api/fern-typescript#549]
There are _a lot_ of custom configuration options in `fern-typescript` - more so than any other generator by a large margin. 

We should revisit the set of options and attempt to reduce them by either removing them or turning them into the default behavior e.g. [`includeUtilsOnUnionMembers`](https://github.com/fern-api/fern-typescript/blob/10590dd2a4fc7ae82b58437b22701bde3b95d37f/packages/generators/sdk/cli/src/custom-config/schema/SdkCustomConfigSchema.ts#L23).

**Comment by dannysheridan** [comment]
closing as a promising idea, but not at this time
