### ISSUE TITLE
Failed to generate a schema 

### ISSUE THREAD

**Issue by krugi** [fern-api/fern-typescript#632]
**Describe the bug**
I get this error:
`src/api/resources/dataAssets/client/Client.ts(515,46): error TS2339: Property 'toISOString' does not exist on type 'string'.`

It seems like it has something to do with the `hour` field 

```json
"ScanStatusEntry": {
  "title": "ScanStatusEntry",
  "required": [
    "size",
    "count",
    "hour"
  ],
  "type": "object",
  "properties": {
    "size": {
      "title": "Size",
      "type": "integer"
    },
    "count": {
      "title": "Count",
      "type": "integer"
    },
    "status": {
      "$ref": "#/components/schemas/ScanStatus"
    },
    "hour": {
      "title": "Hour",
      "type": "string",
      "format": "date-time"
    }
  }
},
```

**To Reproduce**
`fern generate`

**Versions**

- Fern CLI: 0.15.6
- Generator: 0.8.8

**Comment by dsinghvi** [comment]
@krugi this is fixed in the latest release! `0.9.0-rc2`
