### ISSUE TITLE
[Feature] generate pure esm module

### ISSUE THREAD

**Issue by himself65** [fern-api/fern-typescript#642]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dsinghvi** [comment]
@himself65 thanks for filing this issue! we generate cjs currently because it is more compatible, what benefits would there be if we supported esm?

**Comment by himself65** [comment]
Oh, I'm using next.js with RSC support. Seems like there are some issues when importing generated code

<img width="1105" alt="image" src="https://github.com/fern-api/fern-typescript/assets/14026360/93dd0bce-61be-40c5-a2f2-dbb8dcc37285">

**Comment by dsinghvi** [comment]
ahh got it, @himself65 i'll follow up with you next week

**Comment by himself65** [comment]
emit ESM will fix the issue. Thanks
