### ISSUE TITLE
Re-write ideas

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern-typescript#71]
- References should be resolved & imported when parsing the file. Right now we add the import when converting to a type node :(
- Separate File from Context, since some handlers take multiple files (type takes type file, schema file). For some things, it's not clear which SdkFile to use, and it doesn't matter (e.g. resolveType)
- Represent types at a higher level, so you can call `.construct()` to create one and `.declare()` to declare one. Same for functions (`.invoke()`, `.declare()`). This will help with examples

**Comment by dannysheridan** [comment]
closing as stale
